version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hero-factory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hero_factory
      MYSQL_USER: hero_user
      MYSQL_PASSWORD: hero_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

# Volumes persistentes
volumes:
  mysql_data:
    # Volume para armazenar os dados do MySQL 